spring:
  redis:
    host: 123.207.5.185
    password: 123456
    port: 6379
    timeout: 20000
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1
        max-idle: 8

  datasource:
    name:
